exports.facts = [ 
  "A bunch of bananas is called a hand; a single banana is called a finger.",
  "There are more than 1,000 varieties of bananas grown in over 150 countries.",
  "India is the world's biggest banana producer, followed by China.",
  "According to Guiness World Records, the fastest time to eat a banana is 20.33 seconds (2021).",
  "More than 100 billion bananas are eaten each year worldwide.",
  "It's believed that bananas originated about 10,000 years ago and may have been the world's first fruit.",
  "The scientific name for the banana is 'musa sapientum', which translates to 'fruit of the wise men'.",
  "Bananas can float in water.",
  "In Japan, and other cultures, they use the fiber in the banana plant to make fabric and paper.",
  "About 96% of American households buy bananas at least once a month.",
  "Bananas are about 70-75% water.",
  "Bananas are the fourth most consumed plant that we eat.",
  "Potassium, which bananas have in spades, can be used to whiten your teeth.",
  "The average American eats about 25 pounds of bananas every year.",
  "Bananas come in colors other than just yellow -- they come in pink, red, and bright purple too!",
  "The banana plant is classified as a perennial herb and the banana itself is considered a berry.",
  "Portuguese colonisers introduced bananas to the Americas. However, Europeans should thank French writer Jules Verne for introducing them to the fruit.",
  "Bananas contain fiber, potassium, folate and antioxidants such as vitamin C.",
  "Bananas are curved because they are negatively geo-tropic. This means that they grow away from the pull of gravity, growing upward toward the sun.",
  "'Banana' got its name after being sold wrapped in aluminum foil for 10 cents at the 1876 Philadelphia World Fair.",
  "Because of the types of proteins found in bananas, people allergic to bananas are frequently also allergic to latex.",
  "Bananas are scientifically considered a berry, whereas the strawberry is not.",
  "Singers Alicia Keys, Adele, and Katy Perry all have bananas as one of their backstage demands when performing.",
  "The 1971 Woody Allen movie, 'Bananas', made a whopping $11.8 million and appeared in numerous top hit lists, including American Film Institute’s 2000 and AFI’s 100 years 100 laughs.",
  "The oils inside a banana skin can actually help inflammation and itching caused by insect bites.",
  "In 2010, an American man named Ashrita Furman took the title of 'Most Bananas Snapped in 1 Minute', by breaking 99 of them in 60 seconds.",
  "Banana peels are so slippery because of polysaccharide molecules found in them -- a substance also found in our joints.",
  "Hawaii is the only place in the world where bananas are commercially grown.",
  "Because of potassium decay, bananas are naturally radioactive. You are able to die of radiation poisioning if you were able to eat a total of 10 million bananas at once.",
  "Bananas are the only known fruit that is said to help the human body produce serotonin.",
  "Humans share about 50-60% of our DNA with bananas.",
  "In the Philippines, bananas are used in place of tomatoes to make ketchup.",
  "Bananas are considered bad luck on fishing boats.",
  "Wal-mart sells more bananas than any other item.",
  "The name 'banana' is derived from the Arabic word meaning 'finger'.",
  "Guinness World Records claims the biggest bunch of bananas was grown in the Canary Islands, weighing in at 287 pounds and containing 473 single bananas.",
  "The average banana stem can produce up to 240 bananas.",
  "Bananas normally contain large, bitter seeds, but have been selectively bred to produce edible (almost unnoticable) seeds.",
  "August 25th is National Banana Split Day.",
  "National Banana Day, a day for celebrating bananas, is held on the third Wednesday of every April.",
  "A study conducted by the Smell and Taste Treatment Research Foundation found that overweight individuals, after smelling bananas when hungry, lost more weight than those that didn't.",
  "Banana peels are edible (though easier to eat after cooked) and contain carbohydrates, fibre, water and small amounts of protein and fat.",
  "A Chinese study published in 2014 claims that well-ripened bananas help restore and maintain regular bowel functions.",
  "Potassium, which bananas are rich of, help the body's circulatory system delivery oxygen to the brain.",
  "Hungover? Put a couple bananas, some plain yogurt and a little honey into a blender. This combination tends to calm the stomach and the honey helps to restore blood sugar levels back to normal.",
  "A study conducted by the University of Maryland Medical Center says that taping a banana peel over a wart before going to sleep is an effective way to get them to disappear.",
  "You can use the inside of a banana peel to clean and polish leather shoes.",
  "Because of the oil produced in a banana, rubbing the inside of a banana peel on a bug bite or poison ivy will help it from itching and getting inflamed.",
  "The Ugandan word 'matooke' means both 'food' and 'banana'.",
  "Research shows that eating bananas reduces your chance of heart attack and stroke.",
  "More songs have been written about bananas than any other fruit.",
  "Fructooligosaccharides, found in bananas, encourage digestive-friendly probiotics and enhance the body's ability to absorb calcium.",
  "A Swedish study published in 2005 suggests that moderate consumption of bananas may be protective against kidney cancer.",
  "The rarest banana in the world is the Madagascan banana -- only five mature trees exist in the wild as of 2018.",
  "A thief from Mumbai was once forced to eat 48 bananas to help him pass stolen goods he had swallowed.",
  "Andrew Lawrence is known for holding the record of running the fastest marathan dressed as a banana in 2017. He completed it in 2 hours and 47 minutes.",
  "Alexander the Great is credited for discovering the taste of bananas in 327 BC.",
  "There are more trade restrictions on bananas than on AK-47s.",
  "There is a museum in Washington dedicated entirely to banana paraphernalia.",
  "In some parts of Africa, bananas are used to make wine and beer.",
  "The Banana Equivalent Dose is a unit of measurement of radiation.",
  "Slipping on banana peels became a comedic staple after banana peels were deemed a threat to public safety in the late 1800's.",
  "Banana flavoring is based off a compound found in all bananas called isoamyl acetate, unlike the myth that the flavoring was based off of a now-extinct species of bananas.",
  "Bananas don't grow on trees. They are actually giant herbs related to lillies and orchids."
];
